### PR TITLE
Gave Razzy.py some flair

### PR DESCRIPTION
**Pull request by novnod**

### CODE REVIEW

**Comment by novnod** [comment]
Test test much.

**Comment by novnod** [comment]
Waits.

**Comment by rj-py** [comment]
Comments

_Sent from my LGE LGMS330 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rj-py** [comment]
How do u merge anyway?

_Sent from my LGE LGMS330 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
